### ISSUE TITLE
Missing LICENSE? ;-)

### ISSUE THREAD

**Issue by vorburger** [sebastienblanc/vertx-java-tcp-eventbus-bridge#2]
Hello Mr. @sebastienblanc ;-) I would like to have a closer look at this project, but I cannot (and am therefore typing this with eyes shut) because there is no LICENSE here... under what conditions are you making this code available to the world? :-)

If this does what I need for https://github.com/vorburger/minecraft-storeys-maker/issues/58 (TBC), then I would need to be able to depend on it in a build. Assuming that you are not planning to push this to Maven central tomorrow, would you be willing to grant me the permission to simply fork this code into that project, to simplify integration building and future maintenance? NB [that project is AGPL licensed](https://github.com/vorburger/minecraft-storeys-maker/blob/master/LICENSE).

Jokes aside (I'm pretty sure you will be, very, cool with this), it's good to have such things recorded!

**Comment by vorburger** [comment]
> If this does what I need for vorburger/minecraft-storeys-maker#58

actually... I just understood that this uses the Vert.x `TcpEventBusBridge`, whereas I was hoping to find something like this for that `SockJSHandler` ... exposing HTTP instead TCP (instead of pulling another https://github.com/OASIS-learn-study/oc-port-forward-container :smile: trick).

@sebastienblanc @edewit do you happen to know, or can you ask around, if such a thing exists?

**Comment by edewit** [comment]
can't write a little wrapper around this? https://www.eclipse.org/jetty/documentation/9.3.x/jetty-websocket-client-api.html

**Comment by sebastienblanc** [comment]
Added

**Comment by vorburger** [comment]
Saw you chose AGPL - that makes it easy to fork this into vorburger/minecraft-storeys-maker; thanks! :smiley_cat: 

Closing this issue as LICENSE is now available; let's carry on the WebSocket discuss under #3.
